repo_url: "https://github.com/KUB-Education/KUB-Documentation-Space"
site_url: "https://KUB-Education.github.io/KUB-Documentation-Space/"

theme:
  name: material
  logo: 'assets/images/kub-text-logo.svg'
  favicon: 'assets/images/kub-logo.svg'
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: "Switch to light mode"

    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: "Switch to light mode"
  font:
    text: 'e-Ukraine, sans-serif'
    code: 'GeistMono, monospace'
  features:
    - content.full_width

plugins:
  - search
  - awesome-nav
  - swagger-ui-tag:
      supportedSubmitMethods: []

extra_css:
  - 'assets/css/custom.css'
