openapi: "3.1.0"
info:
  title: KUB Account API
  description: Account API for account control on KUB Education platform
  version: 1.0.0-dev
servers:
  - url: https://stage.api.kub.education
    description: Stage Server

paths:
  /api/v1/account/me:
    get:
      summary: "Get user account info"
      operationId: "getCurrentUser"
      security:
        - BearerAuth: []
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            example: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
          description: "Bearer token. Required role: USER"
      responses:
        "200":
          description: "OK"
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/UserDetailsResponse"
  /api/v1/account/change-password:
    post:
      summary: "Change user account password"
      operationId: "changeUserPassword"
      security:
        - BearerAuth: []
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            example: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
          description: "Bearer token. Required role: USER"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserPasswordChangeRequest"
        required: true
      responses:
        "204":
          description: Password changed successfully.
        "400":
          description: Bad Request.
        "401":
          description: Unauthorized.
        "422":
          description: Unprocessable Entity (Validation error).
  /api/v1/account/recovery-password:
    post:
      summary: "Recovery user account password"
      operationId: "recoveryUserPassword"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserPasswordRecoveryRequest"
        required: true
      responses:
        "204":
          description: Password recovery initiated successfully.
        "400":
          description: Bad Request.
        "422":
          description: Unprocessable Entity (Validation error).
components:
  schemas:
    RoleDto:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          nullable: true
        type:
          type: "string"
          nullable: true
          enum:
            - "ORGANIZER"
            - "SYSADMIN"
            - "ADMIN"
            - "LECTURER"
            - "STUDENT"
            - "USER"
    UserDetailsResponse:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          nullable: true
        last_name:
          type: "string"
          nullable: true
        first_name:
          type: "string"
          nullable: true
        middle_name:
          type: "string"
          nullable: true
        email:
          type: "string"
          nullable: true
        status:
          type: "string"
          nullable: true
          enum:
            - "EMAIL_SENDING_FAILURE"
            - "ACTIVATION_PENDING"
            - "ACTIVATION_EXPIRED"
            - "ACTIVATED"
            - "RECOVERY_PENDING"
        roles:
          type: "array"
          nullable: true
          items:
            $ref: "#/components/schemas/RoleDto"
    UserPasswordChangeRequest:
      type: "object"
      properties:
        old_password:
          type: "string"
          nullable: true
        new_password:
          type: "string"
          nullable: true
    Void:
      type: "object"
      properties: {}
    UserPasswordRecoveryRequest:
      type: "object"
      properties:
        email:
          type: "string"
          nullable: true
