nav:
  - Bootstrap API: ./bootstrap/api.md
  - Auth API: ./auth/api.md
  - Account API: ./account/api.md
  - Users API: ./users/api.md
  - Rooms API: ./rooms/api.md
  - Departments API: ./departments/api.md
  - Lecturers API: ./lecturers/api.md
  - Groups API: ./groups/api.md
