nav:
  - Authorization: ./authorization
  - User Management: ./user-management

  - Departments Management: ./departments-management
  - Lecturers Management: ./lecturers-management

  - Study Fields Management: ./study-fields-management
  - Specialties Management: ./specialties-management
  - Educational Programs Management: ./educational-programs-management

  - Students Management: ./students-management

  - Rooms Management: ./rooms-management
