nav:
  - Authorization: ./authorization
  - User Management: ./user-management

  - Departments Management: ./departments-management
  - Lecturers Management: ./lecturers-management

  - Specialties Management: ./specialties-management

  - Rooms Management: ./rooms-management
