openapi: 3.1.0
info:
  title: KUB Specialties API
  description: Specialties API for managing specialties on KUB Education platform
  version: 1.1-dev
servers:
  - url: https://stage.api.kub.education
    description: Stage API Server

paths:
  /specialties:
    post:
      operationId: createSpecialty
      summary: Create a new specialty
      description: > 
        Creates a new specialty with the provided details. 
        Required authority role: admin.
      security:
        - Authorization:
            - admin
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            example: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
          description: Bearer token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SpecialtyRequest"
            examples:
              default:
                value:
                  code: "CS101"
                  name: "Computer Science"
                  fieldOfStudyId: 1
      responses:
        "201":
          $ref: "#/components/responses/Created"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "409":
          $ref: "#/components/responses/Conflict"
        "422":
          $ref: "#/components/responses/UnprocessableEntity"
    
    get:
      operationId: getSpecialtiesByFilters
      summary: Get specialties
      description: > 
        Retrieves a list of all specialties (or by code/name filter).
        Required authority role: anyOf(admin, lecturer, student).
      security:
        - Authorization:
            - admin
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
          example: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        description: Bearer token.
      - name: nameContains
        in: query
        required: false
        schema:
          type: string
          description: The fragment of the name to filter specialties by.
          minLength: 1
          maxLength: 128
      - name: codeContains
        in: query
        required: false
        schema:
          type: string
          description: The fragment of the code to filter specialties by.
          minLength: 1
          maxLength: 32
      responses:
        "200":
          description: Successful retrieval of specialties.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SpecialtyResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "422":
          $ref: "#/components/responses/UnprocessableEntity"

  /specialties/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64

    get:
      operationId: getSpecialtyById
      summary: Get specialty
      description: > 
        Retrieves details of a specific specialty.
        Required authority role: anyOf(admin, lecturer, student).
      security:
        - Authorization:
            - admin
            - lecturer
            - student
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            example: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
          description: Bearer token.
      responses:
        "200":
          description: Successful retrieval of the specialty.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SpecialtyResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"

    put:
      operationId: updateSpecialty
      summary: Edit specialty
      description: > 
        Updates details of a specific specialty. 
        Required authority role: admin.
      security:
        - Authorization:
            - admin
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            example: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
          description: Bearer token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SpecialtyUpdateRequest"
      responses:
        "200":
          description: Successful update of the specialty.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SpecialtyResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"

    delete:
      operationId: deleteSpecialty
      summary: Delete specialty
      description: > 
        Deletes a specialty. 
        Required authority role: admin.
      security:
        - Authorization:
            - admin
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            example: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
          description: Bearer token.
      responses:
        "204":
          $ref: "#/components/responses/NoContent"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"

components:
  responses:
    Created:
      description: Resource created successfully
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/SpecialtyResponse"
    BadRequest:
      description: Bad request (Wrong request parameters)
    Unauthorized:
      description: Unauthorized (Wrong token in Authorization header)
    Forbidden:
      description: Forbidden (Insufficient permissions)
    NotFound:
      description: Not Found (Resource not found)
    NoContent:
      description: No content (Successfully deleted)
    Conflict:
      description: Conflict (Resource already exists)
    UnprocessableEntity:
      description: Unprocessable Entity (Validation error)

  schemas:
    SpecialtyRequest:
      type: object
      required:
        - code
        - name
        - fieldOfStudyId
      properties:
        code:
          type: string
          minLength: 1
          maxLength: 32
        name:
          type: string
          minLength: 1
          maxLength: 128
        fieldOfStudyId:
          type: integer
          format: int64
    
    SpecialtyUpdateRequest:
      type: object
      properties:
        code:
          type: string
          minLength: 1
          maxLength: 32
        name:
          type: string
          minLength: 1
          maxLength: 128
        fieldOfStudyId:
          type: integer
          format: int64

    SpecialtyResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        code:
          type: string
        name:
          type: string
        fieldOfStudyName:
          type: string
