name: Deploy MkDocs Manually

on:
  push:
    branches:
      - master  # Or main if that's your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MkDocs and Dependencies
        run: pip install mkdocs-material mkdocs-awesome-nav mkdocs-swagger-ui-tag

      - name: Build MkDocs Site
        run: mkdocs build

      - name: Deploy to gh-pages Branch
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd site
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add origin https://x-access-token:${GH_TOKEN}@github.com/KUB-Education/KUB-Documentation-Space.git
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy MkDocs site"
          git push --force origin gh-pages
