name: Deploy MkDocs

on:
  push:
    branches:
      - master  # or main, depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MkDocs and Dependencies
        run: pip install mkdocs-material mkdocs-awesome-nav mkdocs-swagger-ui-tag

      - name: Configure Git Authentication
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/KUB-Education/KUB-Documentation-Space.git

      - name: Deploy MkDocs
        run: mkdocs gh-deploy --force
